### PR TITLE
feat(lint): prep for semantic release by enforcing commit style

### PR DESCRIPTION
**Pull request by gergelyke**
This PR preps the repo for adding semantic release, by enforcing the angular commit style.

*But who lints the linters? 🤔*

### CODE REVIEW

**Comment by rkmarks** [comment]
Are we commitng the package-lock.json files now?

**Comment by 3rd-Eden** [comment]
@rkmarks yes, we should be commiting those to git. Ideally with `.gitattributes` setting it as `binary` file so it doesn't cause merge conflicts.

**Comment by 3rd-Eden** [comment]
I honestly don't see the need for linting commit messages here. It only creates a bigger barrier for contributors and it doesn't really add anything to the project. I don't see the reason why we should allow `chore(lint) added linter` vs `[pkg] Added linter` Both achieve the same goal, except for the last one you get yelled at and will be prevented to commit.

**Comment by 3rd-Eden** [comment]
Also if the commit messages of a contributor is up to spec, you can just do a [Squash and merge] on github and alter the commit message.

**Comment by indexzero** [comment]
@3rd-Eden I am relatively new to semantic release, but if I understand it correctly commit messages have to be automatically sanitized to a format so semantic release can understand when to do a patch vs. minor vs. major bump.

I too am not sold on the Angular commit style. It's the holidays – if it's all the same to everyone else would be great to think on this and revisit it in the New Year.

**Comment by 3rd-Eden** [comment]
Regardless of the style used, I feel that declining commits because it doesn't satisfy a certain pattern is a bad pattern. I'm fine with steering people to use a given format. Instead of linting, adoption a [commit.template](https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template) would be more helpful. 

For example, the [pre-commit](https://github.com/observing/pre-commit) allows you specify a template that will be the initial body of the commit which users can fill in.

**Comment by gergelyke** [comment]
Most probably, we don't need the linter at all, and just opt for the analyzeCommit plugin for semantic-release: https://github.com/semantic-release/semantic-release#analyzecommits

**Pull request closed without merging**
