### PR TITLE
[dist] upgrade eslint@3.11, accept minors

### PR DESCRIPTION
**Pull request by Swaagie**
Warrants major release, seems some dist files weren't rebuild either on latest release

### CODE REVIEW

**Comment by jcrugzz** [comment]
@Swaagie we should migrate our jscs rules with this update and get rid of it as necessary piece. https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-from-jscs.md. Not sure if we should get rid of fashion-show or change its use case. Thoughts @indexzero?

**Comment by Swaagie** [comment]
Agree with ^, scope should become bigger to warrant a major release

**Comment by indexzero** [comment]
Happy to get rid of `fashion-show`. It no longer serves a purpose. I've already done all the research on migrating to fully to `eslint` ... just haven't had the time to implement it. The writeup of me research [is here](https://gist.github.com/indexzero/a51afcf01fda7fd2af81932fe72b833c) if anyone feels ambitious.

**Comment by indexzero** [comment]
@Swaagie Travis is failing due to being on `npm@2`:

```
npm ERR! Linux 4.8.7-040807-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.4.7/bin/node" "/home/travis/.nvm/versions/node/v4.4.7/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package eslint@3.11.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-mocha@2.2.0 wants eslint@^2.0.0
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/godaddy/javascript/npm-debug.log
```

We should either make the peer valid or upgrade `.travis.yml` to force upgrade to `npm@3`

**Comment by indexzero** [comment]
Fixed in #40.

**Pull request closed without merging**
